### ISSUE TITLE
如果想把订阅限制从3改到8，需要怎么操作呢

### ISSUE THREAD

**Issue by 1529960009** [666dechaoge/pcrjjc2_xcw#1]

**Comment by 666dechaoge** [comment]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/49865203/1bf9dfa0-e706-40e0-9148-27d52557e6fb)
应该就这里做了限制，你修改下试试看看

**Comment by 1529960009** [comment]
以解决
