### ISSUE TITLE
控制台日志报错，这个是什么原因呢

### ISSUE THREAD

**Issue by 1529960009** [666dechaoge/pcrjjc2_xcw#2]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/08dc03e9-af29-4f77-a4bc-43b319d01ca3)

**Comment by 666dechaoge** [comment]
错误信息 "RemoteDisconected('Remote end closed connection without response)" 表示远程连接意外关闭且没有提供响应。

这个错误可能出现在以下几种情况下：

1. 网络问题：可能是你的设备与远程服务器之间的网络连接出现了中断，导致连接突然关闭。

2. 服务器端问题：远程服务器可能遇到了错误或发生了意外关闭，导致连接在没有响应的情况下被终止。

3. 超时：如果连接期间存在长时间的非活动状态，一些服务器可能会设置超时时间，超过该时间段没有活动就会自动关闭连接。

4. 防火墙或安全设置：你的设备或远程服务器的防火墙或安全措施可能阻止了连接，或者基于安全策略关闭了连接。

针对这个问题，你可以尝试以下步骤进行故障排除：

1. 检查网络连接：确保你的互联网连接稳定，没有出现任何中断。你可以尝试重新启动路由器或通过不同的网络连接，看看问题是否仍然存在。

2. 验证远程服务器状态：如果你可以访问远程服务器，检查它是否正常运行，没有错误或意外关闭。此外，查看服务器日志以获取任何相关信息。

3. 检查防火墙或安全设置：如果你可以控制防火墙或安全设置，请确保它们没有阻止连接。检查是否存在任何可能会过早关闭连接的规则。

如果在尝试了这些步骤之后问题仍然存在，可能需要进一步寻求相关技术支持团队或远程服务器的管理员的帮助。
--from chatgpt

是不是断网了。。。

**Comment by 1529960009** [comment]
用的是腾讯云的服务器啊，国内的。应该不会断网才对

**Comment by 666dechaoge** [comment]
现在还是报错用不了吗

**Comment by 1529960009** [comment]
> 现在还是报错用不了吗

用的了，但是会时不时有上面这个报错

**Comment by 666dechaoge** [comment]
无法重现且一次查询失败不影响正常使用

**Comment by 1529960009** [comment]
![Y}5IU772_F9~W0$GLU02$K4](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/67859171-3c19-45ac-b8aa-b90a30ef4707)
时不时会出现这个报错，并使查询账户重新登录。有部分游戏ID被打提示延迟20/30分钟

**Comment by 666dechaoge** [comment]
> > ![Y}5IU772_F9~W0$GLU02$K4](https://user-images.githubusercontent.com/45947734/243936790-67859171-3c19-45ac-b8aa-b90a30ef4707.png)
> > 时不时会出现这个报错，并使查询账户重新登录。有部分游戏ID被打提示延迟20/30分钟
> 
> 可能是查询300个用户太多了，队列炸了，试着把查询周期调长一些(默认是0.2分钟即12秒)或者再多开一些账号试试，我就测试过最多50个用户。。。一个id大概需要0.3秒，即使5个号在12秒内好像也就能查200个id，另外单次查询偶尔报错正常的，会自动重连上的

拉最新的试试，现在只在队列为空时才加任务

**Comment by 666dechaoge** [comment]
> ![image](https://user-images.githubusercontent.com/45947734/244451064-2807ed3b-655a-4383-b7b4-d326b1f74390.png) ![image](https://user-images.githubusercontent.com/45947734/244451115-671f1c92-e0bf-4de8-b5ab-d898ce77529e.png) 我这边是开了5个号，5个号得状态都可用，查询时间设置的为0.5

少量报错不影响使用
