### ISSUE TITLE
验证码无法发送给管理员

### ISSUE THREAD

**Issue by 1529960009** [666dechaoge/pcrjjc2_xcw#5]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/1ee5dfa8-663f-4b0d-b71c-c73c83afc2e2)
登录时，无法把信息发送给管理员，也未处于风控状态

**Comment by 1529960009** [comment]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/d762f8cf-fdd6-4e96-aab7-73a142e5bef9)
，还未与go-cqhttp客户端建立连接，就执行了发送验证码

**Comment by 666dechaoge** [comment]
改了，试着等待5秒后再发送，看看能发送了吗

**Comment by 1529960009** [comment]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/39597598-9946-428c-91ff-a8214c6fe992)

**Comment by 666dechaoge** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2140

**Comment by 666dechaoge** [comment]
> ![image](https://user-images.githubusercontent.com/45947734/243660842-39597598-9946-428c-91ff-a8214c6fe992.png)

https://github.com/Mrs4s/go-cqhttp/issues/2140
