### ISSUE TITLE
【bug】禁用竞技场推送，依旧会发送排名到群聊，但其他响应指令不触发

### ISSUE THREAD

**Issue by 1529960009** [666dechaoge/pcrjjc2_xcw#7]
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/c832a21f-c750-4709-bc5d-3c18c2b207a8)
![image](https://github.com/666dechaoge/pcrjjc2_xcw/assets/45947734/a7be5b07-89fb-41db-9738-2bd63e7d08fd)

**Comment by 666dechaoge** [comment]
已更新，会过滤掉关闭订阅的群组，再试试
