### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiaomcingn** [666dechaoge/pcrjjc2_xcw#9]
客户端0出错[ValueError('Incorrect AES key length (0 bytes)')]超过3次,可能为网络错误，确认网络正常后,发送pcrlogin 0重试
今天游戏维护更新后就用不了了，试过重启bot也无用。
![4957762e8c6b241df10609262617be47](https://github.com/666dechaoge/pcrjjc2_xcw/assets/63132881/9c45e879-d55c-4dde-9590-b6cf47f0d08f)

**Comment by 666dechaoge** [comment]
已按照pcrjjc2公版提交了修复，更新一下再试试

**Comment by xiaomcingn** [comment]
> 已按照pcrjjc2公版提交了修复，更新一下再试试

遗憾，还是不行，一样的报错

**Comment by xiaomcingn** [comment]
> > 已按照pcrjjc2公版提交了修复，更新一下再试试
> 
> 遗憾，还是不行，一样的报错

哦，没事了已经好了
